python train.py \
    --model='t5' \
    --epochs=100 \
    --lr=2e-4 \
    --batch_size=32 \
    --input_max_len=300 \
    --target_max_len=150 \
    --weight_decay=0.01 \
    --evaluation_strategy='epoch' \
    --save_strategy='epoch' \
    --logging_strategy='epoch' \
    --save_total_limit=100 \
    --train_data_path_FORWARD='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_train.csv' \
    --valid_data_path_FORWARD='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_valid.csv' \
    --test_data_path_FORWARD='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_test.csv' \
    --train_data_path_RETROSYNTHESIS='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_train.csv' \
    --valid_data_path_RETROSYNTHESIS='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_valid.csv' \
    --test_data_path_RETROSYNTHESIS='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_test.csv' \
    --train_data_path_YIELD='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_train.csv' \
    --valid_data_path_YIELD='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_valid.csv' \
    --test_data_path_YIELD='/data1/ReactionT5_neword/data/all_ord_reaction_uniq_with_attr20240506_v3_test.csv' \
    --USPTO_MIT_test_data_path='/data1/ReactionT5_neword/data/USPTO_MIT/MIT_separated/test.csv' \
    --USPTO_50k_test_data_path='/data1/ReactionT5_neword/data/USPTO_50k/test.csv' \
    --CN_test_data_path='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --disable_tqdm \
    --pretrained_model_name_or_path='sagawa/ZINC-t5'
