CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac1_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac1_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac1_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac1_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac1_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac1_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac5_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac5_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac5_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac5_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac5_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac5_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac10_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac10_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac10_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac10_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac10_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac10_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac100_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac100_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac100_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac100_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac100_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test1_frac100_top5similartotestall'


CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac1_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac1_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac1_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac1_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac1_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac1_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac5_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac5_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac5_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac5_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac5_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac5_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac10_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac10_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac10_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac10_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac10_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac10_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac100_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac100_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac100_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac100_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test2/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac100_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test2_frac100_top5similartotestall'


CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac1_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac1_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac1_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac1_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac1_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac1_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac5_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac5_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac5_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac5_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac5_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac5_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac10_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac10_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac10_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac10_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac10_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac10_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac100_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac100_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac100_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac100_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test3/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac100_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test3_frac100_top5similartotestall'


CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac1_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac1_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac1_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac1_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac1_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac1_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac5_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac5_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac5_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac5_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac5_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac5_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac10_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac10_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac10_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac10_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac10_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac10_top5similartotestall'

CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac100_top1similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac100_top1similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac100_top3similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac100_top3similartotestall'
CUDA_VISIBLE_DEVICES=1 python prediction.py \
    --input_data='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test4/test.csv' \
    --model_name_or_path='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac100_top5similartotestall' \
    --batch_size=32 \
    --output_dir='/data1/ReactionT5_neword/task_yield/finetune_v2/finetune_test4_frac100_top5similartotestall'