python train.py \
    --output_dir='400epoch' \
    --epochs=40 \
    --lr=2e-4 \
    --batch_size=32 \
    --input_max_len=300 \
    --target_max_len=150 \
    --weight_decay=0.01 \
    --evaluation_strategy='epoch' \
    --save_strategy='epoch' \
    --logging_strategy='epoch' \
    --save_total_limit=100 \
    --train_data_path_FORWARD='/data1/ReactionT5_neword/data/USPTO_MIT/MIT_separated/train.csv' \
    --valid_data_path_FORWARD='/data1/ReactionT5_neword/data/USPTO_MIT/MIT_separated/val.csv' \
    --train_data_path_RETROSYNTHESIS='/data1/ReactionT5_neword/data/USPTO_50k/train.csv' \
    --valid_data_path_RETROSYNTHESIS='/data1/ReactionT5_neword/data/USPTO_50k/val.csv' \
    --train_data_path_YIELD='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/train.csv' \
    --valid_data_path_YIELD='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --disable_tqdm \
    --pretrained_model_name_or_path='sagawa/CompoundT5'
