CUDA_VISIBLE_DEVICES=2,3 python train.py \
    --output_dir='400epoch' \
    --epochs=400 \
    --lr=2e-4 \
    --batch_size=16 \
    --input_max_len=300 \
    --target_max_len=150 \
    --weight_decay=0.01 \
    --evaluation_strategy='epoch' \
    --save_strategy='epoch' \
    --logging_strategy='epoch' \
    --save_total_limit=100 \
    --train_data_path_YIELD='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/train.csv' \
    --valid_data_path_YIELD='/data1/ReactionT5_neword/data/C_N_yield/MFF_Test1/test.csv' \
    --disable_tqdm \
    --pretrained_model_name_or_path='sagawa/CompoundT5'
